##
# @author: @Med'eZ
#

# Application config
# -------------------
app:
  app_name: emodash
  title: My starter @Med'eZ
  template: src/index.html
  src_folder: src
  description: ''
  main_file: main.ts
  vendors_file: vendors.browser.ts

# Build & Bundle config
# -------------------
build:
  dist_folder: dist
  js_bundle_name: bundle.js

# Env config
# -------------------
env:
  dev: &dev
    host: localhost
    port: 3000

  prod:
    <<: *dev

  test:
    <<: *dev

